image: php:7.4

variables:
  POSTGRES_DB: $POSTGRES_DB
  POSTGRES_USER: $POSTGRES_USER
  POSTGRES_PASSWORD: $POSTGRES_PASSWORD
  POSTGRES_HOST_AUTH_METHOD: trust

cache:
  paths:
    - ./vendor/

services:
  - postgres:12.2-alpine

stages:
  - build
  - deploy
payment-build:
  stage: build
  before_script:
    - cd payment
    - ls
    - apt update -y
    - pecl install xdebug
    - docker-php-ext-enable xdebug
    - apt install -y libzip-dev zip
    - docker-php-ext-install pdo pdo_mysql zip
    - curl -sS https://getcomposer.org/installer | php
    - mv composer.phar /usr/local/bin/composer
  script:
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress -d .
  only:
    - main

payment-deploy:
  type: deploy
  image : ruby:latest
  script:
    - cd payment
    - ls
    - curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_PROD --api-key=$HEROKU_API_KEY
    - heroku run php bin/console d:s:u --force --exit-code --app $HEROKU_APP_PROD
  only:
    - main