parameters:
    # ...
    env(ELASTICSEARCH_HOST): 'http://localhost:9200'

api_platform:
    title: Hello API Platform
    version: 1.0.0
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    elasticsearch:
        hosts: [ '%env(ELASTICSEARCH_HOST)%' ]
    patch_formats:
        json: ['application/json']
    swagger:
        api_keys:
            apiKey:
                name: Authorization
                type: header
    # Mercure integration, remove if unwanted
    mercure:
        hub_url: '%env(MERCURE_SUBSCRIBE_URL)%'

    eager_loading:
        fetch_partial: true